set MASMX=masmx
set FLAGS=-kw
@echo off
del /Q  ..\test.rta\*
%MASMX% %FLAGS% 2part.msm ..\test.rta\2part
%MASMX% %FLAGS% absolute.msm ..\test.rta\absolute
%MASMX% %FLAGS% ap1.msm ..\test.rta\ap1
%MASMX% %FLAGS% ap2.msm ..\test.rta\ap2
%MASMX% %FLAGS% ap3.msm ..\test.rta\ap3
%MASMX% %FLAGS% -Z ap3.msm ..\test.rta\ap3z
%MASMX% %FLAGS% aplical.msm ..\test.rta\aplical
%MASMX% %FLAGS% applaud.msm ..\test.rta\applaud
%MASMX% %FLAGS% application.msm ..\test.rta\application
%MASMX% %FLAGS% aqt.msm ..\test.rta\aqt
%MASMX% %FLAGS% array.msm ..\test.rta\array
%MASMX% %FLAGS% array2.msm ..\test.rta\array2
%MASMX% %FLAGS% arrester.msm ..\test.rta\arrester
%MASMX% %FLAGS% arrow.msm ..\test.rta\arrow
%MASMX% %FLAGS% att.msm ..\test.rta\att
%MASMX% %FLAGS% attestor.msm ..\test.rta\attestor
%MASMX% %FLAGS% awibiti.msm ..\test.rta\awibiti
%MASMX% %FLAGS% base_d.msm ..\test.rta\base_d
%MASMX% %FLAGS% basis.msm ..\test.rta\basis
%MASMX% %FLAGS% betaille.msm ..\test.rta\betaille
%MASMX% %FLAGS% bitmodel.msm ..\test.rta\bitmodel
%MASMX% %FLAGS% bloc_fun.msm ..\test.rta\bloc_fun
%MASMX% %FLAGS% boolean.msm ..\test.rta\boolean
%MASMX% %FLAGS% brin.msm ..\test.rta\brin
%MASMX% %FLAGS% bsti.msm ..\test.rta\bsti
%MASMX% %FLAGS% call4u.msm ..\test.rta\call4u
%MASMX% %FLAGS% catalog.msm ..\test.rta\catalog
%MASMX% %FLAGS% cdml.msm ..\test.rta\cdml
%MASMX% %FLAGS% chaos.msm ..\test.rta\chaos
%MASMX% %FLAGS% clatter.msm ..\test.rta\clatter
%MASMX% %FLAGS% clibel.msm ..\test.rta\clibel
%MASMX% %FLAGS% cluster.msm ..\test.rta\cluster
%MASMX% %FLAGS% colibri.msm ..\test.rta\colibri
%MASMX% %FLAGS% collect.msm ..\test.rta\collect
%MASMX% %FLAGS% columns.msm ..\test.rta\columns
%MASMX% %FLAGS% complete.msm ..\test.rta\complete
%MASMX% %FLAGS% context.msm ..\test.rta\context
%MASMX% %FLAGS% cs2i.msm ..\test.rta\cs2i
%MASMX% %FLAGS% cstrings.msm ..\test.rta\cstrings
%MASMX% %FLAGS% dmsa.msm ..\test.rta\dmsa
%MASMX% %FLAGS% dmsample.msm ..\test.rta\dmsample
%MASMX% %FLAGS% directio.msm ..\test.rta\directio
%MASMX% %FLAGS% du.msm ..\test.rta\du
%MASMX% %FLAGS% elephant.msm ..\test.rta\elephant
%MASMX% %FLAGS% expand.msm ..\test.rta\expand
%MASMX% %FLAGS% expound.msm ..\test.rta\expound
%MASMX% %FLAGS% feeler.msm ..\test.rta\feeler
%MASMX% %FLAGS% fields.msm ..\test.rta\fields
%MASMX% %FLAGS% floatate.msm ..\test.rta\floatate
%MASMX% %FLAGS% floating.msm ..\test.rta\floating
%MASMX% %FLAGS% fpfactor.msm ..\test.rta\fpfactor
%MASMX% %FLAGS% fplen.msm ..\test.rta\fplen
%MASMX% %FLAGS% fp_array.msm ..\test.rta\fp_array
%MASMX% %FLAGS% funs.msm ..\test.rta\funs
%MASMX% %FLAGS% gamp.msm ..\test.rta\gamp
%MASMX% %FLAGS% gant.msm ..\test.rta\gant
%MASMX% %FLAGS% gap.msm ..\test.rta\gap
%MASMX% %FLAGS% harness1.msm ..\test.rta\harness1
%MASMX% %FLAGS% horror.msm ..\test.rta\horror
%MASMX% %FLAGS% iarrayl.msm ..\test.rta\iarrayl
%MASMX% %FLAGS% ibj.msm ..\test.rta\ibj
%MASMX% -lnk idio.msm ..\test.rta\idio > newlist.txt
%MASMX% %FLAGS% ilib12.msm ..\test.rta\ilib12
%MASMX% %FLAGS% ilib16.msm ..\test.rta\ilib16
%MASMX% %FLAGS% ilib16z.msm ..\test.rta\ilib16z
%MASMX% %FLAGS% ilib6.msm ..\test.rta\ilib6
%MASMX% %FLAGS% ilib24.msm ..\test.rta\ilib24
%MASMX% %FLAGS% ilib.msm ..\test.rta\ilib
%MASMX% %FLAGS% index.msm ..\test.rta\index
%MASMX% %FLAGS% indicate.msm ..\test.rta\indicate
%MASMX% %FLAGS% ipproto.msm ..\test.rta\ipproto
%MASMX% %FLAGS% isit.msm ..\test.rta\isit
%MASMX% %FLAGS% istrubl.msm ..\test.rta\istrubl
%MASMX% %FLAGS% klaousin.msm ..\test.rta\klaousin
%MASMX% %FLAGS% large.msm ..\test.rta\large
%MASMX% %FLAGS% leftala.msm ..\test.rta\leftala
%MASMX% %FLAGS% leveler.msm ..\test.rta\leveler
%MASMX% %FLAGS% levels.msm ..\test.rta\levels
%MASMX% %FLAGS% linkrel.msm ..\test.rta\linkrel
%MASMX% %FLAGS% loademup.msm ..\test.rta\loademup
%MASMX% %FLAGS% loadg.msm ..\test.rta\loadg
%MASMX% %FLAGS% log2.msm ..\test.rta\log2
%MASMX% %FLAGS% lquick.msm ..\test.rta\lquick
%MASMX% %FLAGS% lsi.msm ..\test.rta\lsi
%MASMX% %FLAGS% lsif.msm ..\test.rta\lsif
%MASMX% %FLAGS% lsii.msm ..\test.rta\lsii
%MASMX% %FLAGS% lstruct.msm ..\test.rta\lstruct
%MASMX% %FLAGS% madstuff.msm ..\test.rta\madstuff
%MASMX% %FLAGS% main.msm ..\test.rta\main
%MASMX% %FLAGS% mammoth.msm ..\test.rta\mammoth
%MASMX% %FLAGS% maru.msm ..\test.rta\maru
%MASMX% %FLAGS% mijo.msm ..\test.rta\mijo
%MASMX% %FLAGS% miklthon.msm ..\test.rta\miklthon
%MASMX% %FLAGS% mstrlib.msm ..\test.rta\mstrlib
%MASMX% %FLAGS% muklthon.msm ..\test.rta\muklthon
%MASMX% %FLAGS% nawmuch.msm ..\test.rta\nawmuch
%MASMX% %FLAGS% newaudit.msm ..\test.rta\newaudit
%MASMX% %FLAGS% newtotal.msm ..\test.rta\newtotal
%MASMX% %FLAGS% normal.msm ..\test.rta\normal
%MASMX% %FLAGS% oh.msm ..\test.rta\oh
%MASMX% %FLAGS% once.msm ..\test.rta\once
%MASMX% %FLAGS% onetime.msm ..\test.rta\onetime
%MASMX% %FLAGS% oreally.msm ..\test.rta\oreally
%MASMX% %FLAGS% oreilly.msm ..\test.rta\oreilly
%MASMX% %FLAGS% overlap.msm ..\test.rta\overlap
%MASMX% %FLAGS% overlay.msm ..\test.rta\overlay
%MASMX% %FLAGS% p1.msm ..\test.rta\p1
%MASMX% %FLAGS% p2.msm ..\test.rta\p2
%MASMX% %FLAGS% p3.msm ..\test.rta\p3
%MASMX% %FLAGS% paxels.msm ..\test.rta\paxels
%MASMX% %FLAGS% point.msm ..\test.rta\point
%MASMX% %FLAGS% pointer.msm ..\test.rta\pointer
%MASMX% %FLAGS% pointers.msm ..\test.rta\pointers
%MASMX% %FLAGS% pungs.msm ..\test.rta\pungs
%MASMX% %FLAGS% px8.msm ..\test.rta\px8
%MASMX% %FLAGS% pygmalio.msm ..\test.rta\pygmalio
%MASMX% %FLAGS% q.msm ..\test.rta\q
%MASMX% %FLAGS% quadlib.msm ..\test.rta\quadlib
%MASMX% %FLAGS% quickly.msm ..\test.rta\quickly
%MASMX% %FLAGS% r2xample.msm ..\test.rta\r2xample
%MASMX% %FLAGS% r3xample.msm ..\test.rta\r3xample
%MASMX% %FLAGS% rabits.msm ..\test.rta\rabits
%MASMX% %FLAGS% raft.msm ..\test.rta\raft
%MASMX% %FLAGS% randomsi ..\test.rta\randomsi
%MASMX% %FLAGS% rangy ..\test.rta\rangy
%MASMX% %FLAGS% rasm.msm ..\test.rta\rasm
%MASMX% %FLAGS% record.msm ..\test.rta\record
%MASMX% %FLAGS% recurseg.msm ..\test.rta\recurseg
%MASMX% %FLAGS% refine.msm ..\test.rta\refine
%MASMX% %FLAGS% regula.msm ..\test.rta\regula
%MASMX% %FLAGS% rei.msm ..\test.rta\rei
%MASMX% %FLAGS% relarith.msm ..\test.rta\relarith
%MASMX% %FLAGS% relocate.msm ..\test.rta\relocate
%MASMX% %FLAGS% ribble.msm ..\test.rta\ribble
%MASMX% %FLAGS% rodel.msm ..\test.rta\rodel
%MASMX% %FLAGS% rtable.msm ..\test.rta\rtable
%MASMX% %FLAGS% s.msm ..\test.rta\s
%MASMX% %FLAGS% s2i.msm ..\test.rta\s2i
%MASMX% %FLAGS% salute.msm ..\test.rta\salute
%MASMX% %FLAGS% sand46.msm ..\test.rta\sand46
%MASMX% %FLAGS% sand46_2.msm ..\test.rta\sand46_2
%MASMX% %FLAGS% sand5.msm ..\test.rta\sand5
%MASMX% %FLAGS% sand5_2.msm ..\test.rta\sand5_2
%MASMX% %FLAGS% sandwich.msm ..\test.rta\sandwich
%MASMX% %FLAGS% schema.msm ..\test.rta\schema
%MASMX% %FLAGS% schema1.msm ..\test.rta\schema1
%MASMX% %FLAGS% seeabout.msm ..\test.rta\seeabout
%MASMX% %FLAGS% sema.msm ..\test.rta\sema
%MASMX% %FLAGS% semi.msm ..\test.rta\semi
%MASMX% %FLAGS% sevenup.msm ..\test.rta\sevenup
%MASMX% %FLAGS% shadow.msm ..\test.rta\shadow
%MASMX% %FLAGS% shadow1.msm ..\test.rta\shadow1
%MASMX% %FLAGS% shuttle.msm ..\test.rta\shuttle
%MASMX% %FLAGS% simply.msm ..\test.rta\simply -c
%MASMX% %FLAGS% sizes.msm ..\test.rta\sizes
%MASMX% %FLAGS% slappit.msm ..\test.rta\slappit
%MASMX% %FLAGS% sokens.msm ..\test.rta\sokens
%MASMX% %FLAGS% sort_out.msm ..\test.rta\sort_out
%MASMX% %FLAGS% sowino.msm ..\test.rta\sowino
lstring -b ..\test.rta\sowino.txo ..\test.rta\sowino
%MASMX% %FLAGS% soyuno.msm ..\test.rta\soyuno
%MASMX% %FLAGS% spiko.msm ..\test.rta\spiko
%MASMX% %FLAGS% splices.msm ..\test.rta\splices
%MASMX% %FLAGS% spoka.msm ..\test.rta\spoka
%MASMX% %FLAGS% step1.msm ..\test.rta\step1
%MASMX% %FLAGS% step2.msm ..\test.rta\step2
%MASMX% %FLAGS% step3.msm ..\test.rta\step3
%MASMX% %FLAGS% step4.msm ..\test.rta\step4
%MASMX% %FLAGS% stredit.msm ..\test.rta\stredit
%MASMX% %FLAGS% subsequf ..\test.rta\subsequf
%MASMX% %FLAGS% suitable.msm ..\test.rta\suitable
%MASMX% %FLAGS% symbo.msm ..\test.rta\symbo
%MASMX% %FLAGS% tcolumn.msm ..\test.rta\tcolumn
%MASMX% %FLAGS% tptr.msm ..\test.rta\tptr
%MASMX% %FLAGS% trumpet.msm ..\test.rta\trumpet -X
%MASMX% %FLAGS% tryhard.msm ..\test.rta\tryhard
%MASMX% %FLAGS% types.msm ..\test.rta\types
%MASMX% %FLAGS% unary.msm ..\test.rta\unary
%MASMX% %FLAGS% unary2.msm ..\test.rta\unary2
%MASMX% %FLAGS% unlikely.msm ..\test.rta\unlikely
%MASMX% %FLAGS% velours.msm ..\test.rta\velours
%MASMX% %FLAGS% visible.msm ..\test.rta\visible
%MASMX% %FLAGS% where.msm ..\test.rta\where
pushd ..\multadic
%MASMX% %FLAGS% multadic ..\test.rta\multadic
cd ..\language
%MASMX% %FLAGS% fpxample ..\test.rta\fpxample
%MASMX% %FLAGS% fpxpress ..\test.rta\fpxpress
%MASMX% %FLAGS% i_xpr ..\test.rta\i_xpr
%MASMX% %FLAGS% individu ..\test.rta\individu
%MASMX% %FLAGS% r2xample ..\test.rta\r2xample
%MASMX% %FLAGS% ..\language\rtxample ..\test.rta\rtxample
popd
pushd oper8
%MASMX% %FLAGS% oper8 ..\..\test.rta\oper8
%MASMX% %FLAGS% -I tsoper8 ..\..\test.rta\tsoper8
popd
@echo on
seeif -avVW list.txt newlist.txt

seeif -a ../result.rta ../test.rta
