del ..\test.rta\*
masmx -wk absolute.msm ..\test.rta\absolute
masmx -wk ap1.msm ..\test.rta\ap1
masmx -wk ap2.msm ..\test.rta\ap2
masmx -wk ap3.msm ..\test.rta\ap3
masmx -wk -Z ap3.msm ..\test.rta\ap3z
masmx -wk applaud.msm ..\test.rta\applaud
masmx -wk application.msm ..\test.rta\application
masmx -wk aqt.msm ..\test.rta\aqt
masmx -wk array.msm ..\test.rta\array
masmx -wk array2.msm ..\test.rta\array2
masmx -wk arrester.msm ..\test.rta\arrester
masmx -wk arrow.msm ..\test.rta\arrow
masmx -wk att.msm ..\test.rta\att
masmx -wk attestor.msm ..\test.rta\attestor
masmx -wk awibiti.msm ..\test.rta\awibiti
masmx -wk base_d.msm ..\test.rta\base_d
masmx -wk basis.msm ..\test.rta\basis
masmx -wk betaille.msm ..\test.rta\betaille
masmx -wk bloc_fun.msm ..\test.rta\bloc_fun
masmx -wk boolean.msm ..\test.rta\boolean
masmx -wk brin.msm ..\test.rta\brin
masmx -wk bsti.msm ..\test.rta\bsti
masmx -wk call4u.msm ..\test.rta\call4u
masmx -wk catalog.msm ..\test.rta\catalog
masmx -wk cdml.msm ..\test.rta\cdml
masmx -wk chaos.msm ..\test.rta\chaos
masmx -wk clatter.msm ..\test.rta\clatter
masmx -wk clibel.msm ..\test.rta\clibel
masmx -wk cluster.msm ..\test.rta\cluster
masmx -wk colibri.msm ..\test.rta\colibri
masmx -wk collect.msm ..\test.rta\collect
masmx -wk columns.msm ..\test.rta\columns
masmx -wk complete.msm ..\test.rta\complete
masmx -wk context.msm ..\test.rta\context
masmx -wk cs2i.msm ..\test.rta\cs2i
masmx -wk cstrings.msm ..\test.rta\cstrings
masmx -wk dmsa.msm ..\test.rta\dmsa
masmx -wk dmsample.msm ..\test.rta\dmsample
masmx -wk directio.msm ..\test.rta\directio
masmx -wk du.msm ..\test.rta\du
masmx -wk elephant.msm ..\test.rta\elephant
masmx -wk expand.msm ..\test.rta\expand
masmx -wk expound.msm ..\test.rta\expound
masmx -wk floating.msm ..\test.rta\floating
masmx -wk fpfactor.msm ..\test.rta\fpfactor
masmx -wk fplen.msm ..\test.rta\fplen
masmx -wk fp_array.msm ..\test.rta\fp_array
masmx -wk funs.msm ..\test.rta\funs
masmx -wk gamp.msm ..\test.rta\gamp
masmx -wk gant.msm ..\test.rta\gant
masmx -wk gap.msm ..\test.rta\gap
masmx -wk harness1.msm ..\test.rta\harness1
masmx -wk horror.msm ..\test.rta\horror
masmx -wk iarrayl.msm ..\test.rta\iarrayl
masmx -wk ibj.msm ..\test.rta\ibj
masmx -lnk idio.msm ..\test.rta\idio > newlist.txt
masmx -wk ilib12.msm ..\test.rta\ilib12
masmx -wk ilib16.msm ..\test.rta\ilib16
masmx -wk ilib16z.msm ..\test.rta\ilib16z
masmx -wk ilib6.msm ..\test.rta\ilib6
masmx -wk ilib24.msm ..\test.rta\ilib24
masmx -wk ilib.msm ..\test.rta\ilib
masmx -wk indicate.msm ..\test.rta\indicate
masmx -wk ipproto.msm ..\test.rta\ipproto
masmx -wk istrubl.msm ..\test.rta\istrubl
masmx -wk large.msm ..\test.rta\large
masmx -wk leftala.msm ..\test.rta\leftala
masmx -wk leveler.msm ..\test.rta\leveler
masmx -wk levels.msm ..\test.rta\levels
masmx -wk linkrel.msm ..\test.rta\linkrel
masmx -wk loademup.msm ..\test.rta\loademup
masmx -wk loadg.msm ..\test.rta\loadg
masmx -wk log2.msm ..\test.rta\log2
masmx -wk lquick.msm ..\test.rta\lquick
masmx -wk lstruct.msm ..\test.rta\lstruct
masmx -wk main.msm ..\test.rta\main
masmx -wk mammoth.msm ..\test.rta\mammoth
masmx -wk maru.msm ..\test.rta\maru
masmx -wk miklthon.msm ..\test.rta\miklthon
masmx -wk mstrlib.msm ..\test.rta\mstrlib
masmx -wk muklthon.msm ..\test.rta\muklthon
masmx -wk nawmuch.msm ..\test.rta\nawmuch
masmx -wk newtotal.msm ..\test.rta\newtotal
masmx -wk once.msm ..\test.rta\once
masmx -wk onetime.msm ..\test.rta\onetime
masmx -wk oreally.msm ..\test.rta\oreally
masmx -wk oreilly.msm ..\test.rta\oreilly
masmx -wk overlap.msm ..\test.rta\overlap
masmx -wk overlay.msm ..\test.rta\overlay
masmx -wk p1.msm ..\test.rta\p1
masmx -wk p2.msm ..\test.rta\p2
masmx -wk p3.msm ..\test.rta\p3
masmx -wk paxels.msm ..\test.rta\paxels
masmx -wk point.msm ..\test.rta\point
masmx -wk pointer.msm ..\test.rta\pointer
masmx -wk pointers.msm ..\test.rta\pointers
masmx -wk pungs.msm ..\test.rta\pungs
masmx -wk px8.msm ..\test.rta\px8
masmx -wk pygmalio.msm ..\test.rta\pygmalio
masmx -wk q.msm ..\test.rta\q
masmx -wk quadlib.msm ..\test.rta\quadlib
masmx -wk quickly.msm ..\test.rta\quickly
masmx -wk rabits.msm ..\test.rta\rabits
masmx -wk raft.msm ..\test.rta\raft
masmx -wk randomsi ..\test.rta\randomsi
masmx -wk rangy ..\test.rta\rangy
masmx -wk rasm.msm ..\test.rta\rasm
masmx -wk record.msm ..\test.rta\record
masmx -wk recurseg.msm ..\test.rta\recurseg
masmx -wk refine.msm ..\test.rta\refine
masmx -wk rei.msm ..\test.rta\rei
masmx -wk relarith.msm ..\test.rta\relarith
masmx -wk relocate.msm ..\test.rta\relocate
masmx -wk rodel.msm ..\test.rta\rodel
masmx -wk rtable.msm ..\test.rta\rtable
masmx -wk s2i.msm ..\test.rta\s2i
masmx -wk salute.msm ..\test.rta\salute
masmx -wk sand46.msm ..\test.rta\sand46
masmx -wk sand46_2.msm ..\test.rta\sand46_2
masmx -wk sand5.msm ..\test.rta\sand5
masmx -wk sand5_2.msm ..\test.rta\sand5_2
masmx -wk sandwich.msm ..\test.rta\sandwich
masmx -wk schema.msm ..\test.rta\schema
masmx -wk schema1.msm ..\test.rta\schema1
masmx -wk sema.msm ..\test.rta\sema
masmx -wk semi.msm ..\test.rta\semi
masmx -wk shadow.msm ..\test.rta\shadow
masmx -wk shadow1.msm ..\test.rta\shadow1
masmx -wk shuttle.msm ..\test.rta\shuttle
masmx -wk simply.msm ..\test.rta\simply -c
masmx -wk sizes.msm ..\test.rta\sizes
masmx -wk slappit.msm ..\test.rta\slappit
masmx -wk sort_out.msm ..\test.rta\sort_out
masmx -wk sowino.msm ..\test.rta\sowino
lstring -b ..\test.rta\sowino.txo ..\test.rta\sowino
masmx -wk soyuno.msm ..\test.rta\soyuno
masmx -wk spiko.msm ..\test.rta\spiko
masmx -wk splices.msm ..\test.rta\splices
masmx -wk spoka.msm ..\test.rta\spoka
masmx -wk step1.msm ..\test.rta\step1
masmx -wk step2.msm ..\test.rta\step2
masmx -wk step3.msm ..\test.rta\step3
masmx -wk step4.msm ..\test.rta\step4
masmx -wk stredit.msm ..\test.rta\stredit
masmx -wk subsequf ..\test.rta\subsequf
masmx -wk symbo.msm ..\test.rta\symbo
masmx -wk tcolumn.msm ..\test.rta\tcolumn
masmx -wk tptr.msm ..\test.rta\tptr
masmx -wk tryhard.msm ..\test.rta\tryhard
masmx -wk types.msm ..\test.rta\types
masmx -wk unary.msm ..\test.rta\unary
masmx -wk unary2.msm ..\test.rta\unary2
masmx -wk unlikely.msm ..\test.rta\unlikely
masmx -wk velours.msm ..\test.rta\velours
masmx -wk visible.msm ..\test.rta\visible
masmx -wk where.msm ..\test.rta\where
pushd ..\multadic
masmx -wk multadic ..\test.rta\multadic
cd ..\language
masmx -wk fpxample ..\test.rta\fpxample
masmx -wk fpxpress ..\test.rta\fpxpress
masmx -wk i_xpr ..\test.rta\i_xpr
masmx -wk individu ..\test.rta\individu
masmx -wk r2xample ..\test.rta\r2xample
popd
seeif -asvVW list.txt newlist.txt

