del ..\test.rta\*
masmx -kw absolute.msm ..\test.rta\absolute
masmx -kw ap1.msm ..\test.rta\ap1
masmx -kw ap2.msm ..\test.rta\ap2
masmx -kw ap3.msm ..\test.rta\ap3
masmx -kw applaud.msm ..\test.rta\applaud
masmx -kw application.msm ..\test.rta\application
masmx -kw aqt.msm ..\test.rta\aqt
masmx -kw array.msm ..\test.rta\array
masmx -kw array2.msm ..\test.rta\array2
masmx -kw arrester.msm ..\test.rta\arrester
masmx -kw arrow.msm ..\test.rta\arrow
masmx -kw att.msm ..\test.rta\att
masmx -kw awibiti.msm ..\test.rta\awibiti
masmx -kw base_d.msm ..\test.rta\base_d
masmx -kw basis.msm ..\test.rta\basis
masmx -kw betaille.msm ..\test.rta\betaille
masmx -kw boolean.msm ..\test.rta\boolean
masmx -kw brin ..\test.rta\brin
masmx -kw catalog.msm ..\test.rta\catalog
masmx -kw call4u ..\test.rta\call4u
masmx -kw chaos.msm ..\test.rta\chaos
masmx -kw clatter.msm ..\test.rta\clatter
masmx -kw clibel ..\test.rta\clibel
masmx -kw cluster.msm ..\test.rta\cluster
masmx -kw colibri.msm ..\test.rta\colibri
masmx -kw collect.msm ..\test.rta\collect
masmx -kw columns.msm ..\test.rta\columns
masmx -kw complete.msm ..\test.rta\complete
masmx -kw context.msm ..\test.rta\context
masmx -kw directio.msm ..\test.rta\directio
masmx -kw du.msm ..\test.rta\du
masmx -kw elephant.msm ..\test.rta\elephant
masmx -kw floating.msm ..\test.rta\floating
masmx -kw fpfactor.msm ..\test.rta\fpfactor
masmx -kw fplen.msm ..\test.rta\fplen
masmx -kw fp_array.msm ..\test.rta\fp_array
masmx -kw funs ..\test.rta\funs
masmx -kw gamp.msm ..\test.rta\gamp
masmx -kw gant.msm ..\test.rta\gant
masmx -kw gap.msm ..\test.rta\gap
masmx -kw iarrayl.msm ..\test.rta\iarrayl
masmx -kw ibj.msm ..\test.rta\ibj
masmx -kw ilib12.msm ..\test.rta\ilib12
masmx -kw ilib16.msm ..\test.rta\ilib16
masmx -kw ilib16z.msm ..\test.rta\ilib16z
masmx -kw ilib6.msm ..\test.rta\ilib6
masmx -kw ilib24.msm ..\test.rta\ilib24
masmx -kw ilib.msm ..\test.rta\ilib
masmx -kw indicate.msm ..\test.rta\indicate
masmx -kw ipproto.msm ..\test.rta\ipproto
masmx -kw leftala.msm ..\test.rta\leftala
masmx -kw leveler.msm ..\test.rta\leveler
masmx -kw levels.msm ..\test.rta\levels
masmx -kw linkrel.msm ..\test.rta\linkrel
masmx -kw loademup.msm ..\test.rta\loademup
masmx -kw loadg.msm ..\test.rta\loadg
masmx -kw log2.msm ..\test.rta\log2
masmx -kw lquick.msm ..\test.rta\lquick
masmx -kw lstruct.msm ..\test.rta\lstruct
masmx -kw main.msm ..\test.rta\main
masmx -kw mammoth.msm ..\test.rta\mammoth
masmx -kw maru.msm ..\test.rta\maru
masmx -kw miklthon.msm ..\test.rta\miklthon
masmx -kw mstrlib ..\test.rta\mstrlib
masmx -kw muklthon.msm ..\test.rta\muklthon
masmx -kw nawmuch.msm ..\test.rta\nawmuch
masmx -kw newtotal.msm ..\test.rta\newtotal
masmx -kw once.msm ..\test.rta\once
masmx -kw onetime.msm ..\test.rta\onetime
masmx -kw online2A ..\test.rta\online2A
masmx -kw oreally.msm ..\test.rta\oreally
masmx -kw oreilly.msm ..\test.rta\oreilly
masmx -kw overlap ..\test.rta\overlap
masmx -kw overlay.msm ..\test.rta\overlay
masmx -kw paxels ..\test.rta\paxels
masmx -kw pointer.msm ..\test.rta\pointer
masmx -kw pungs ..\test.rta\pungs
masmx -kw q.msm ..\test.rta\q
masmx -kw quadlib ..\test.rta\quadlib
masmx -kw quickly.msm ..\test.rta\quickly
masmx -kw r2xample ..\test.rta\r2xample
masmx -kw raft ..\test.rta\raft
masmx -kw rasm.msm ..\test.rta\rasm
masmx -kw randomsi ..\test.rta\randomsi
masmx -kw record.msm ..\test.rta\record
masmx -kw recurseg.msm ..\test.rta\recurseg
masmx -kw refine.msm ..\test.rta\refine
masmx -kw rei.msm ..\test.rta\rei
masmx -kw relarith.msm ..\test.rta\relarith
masmx -kw rtable ..\test.rta\rtable
masmx -kw relocate.msm ..\test.rta\relocate
masmx -kw salute.msm ..\test.rta\salute
masmx -kw sema.msm ..\test.rta\sema
masmx -kw semi.msm ..\test.rta\semi
masmx -kw shadow.msm ..\test.rta\shadow
masmx -kw shadow1.msm ..\test.rta\shadow1
masmx -kw shuttle.msm ..\test.rta\shuttle
masmx -kw simply.msm ..\test.rta\simply -c
masmx -kw sizes.msm ..\test.rta\sizes
masmx -kw sort_out.msm ..\test.rta\sort_out
masmx -kw sowino.msm ..\test.rta\sowino
lstring -b ..\test.rta\sowino.txo ..\test.rta\sowino
masmx -kw soyuno.msm ..\test.rta\soyuno
masmx -kw spiko.msm ..\test.rta\spiko
masmx -kw splices.msm ..\test.rta\splices
masmx -kw spoka.msm ..\test.rta\spoka
masmx -kw step1.msm ..\test.rta\step1
masmx -kw step2.msm ..\test.rta\step2
masmx -kw step3.msm ..\test.rta\step3
masmx -kw step4.msm ..\test.rta\step4
masmx -kw stredit.msm ..\test.rta\stredit
masmx -kw symbo.msm ..\test.rta\symbo
masmx -kw tcolumn.msm ..\test.rta\tcolumn
masmx -kw tptr.msm ..\test.rta\tptr
masmx -kw types.msm ..\test.rta\types
masmx -kw unary.msm ..\test.rta\unary
masmx -kw unary2.msm ..\test.rta\unary2
masmx -kw unlikely.msm ..\test.rta\unlikely
masmx -kw velours.msm ..\test.rta\velours
masmx -kw visible.msm ..\test.rta\visible
masmx -kw w7.msm ..\test.rta\w7
pushd ..\multadic
masmx -kw multadic ..\test.rta\multadic
cd ..\language
masmx -kw fpxample ..\test.rta\fpxample
masmx -kw fpxpress ..\test.rta\fpxpress
masmx -kw i_xpr ..\test.rta\i_xpr
masmx -kw individu ..\test.rta\individu
masmx -kw r2xample ..\test.rta\r2xample
popd

