del ..\test.rta\*
masmx -kw absolute.msm ..\test.rta\absolute
masmx -kw ap1.msm ..\test.rta\ap1
masmx -kw ap2.msm ..\test.rta\ap2
masmx -kw ap3.msm ..\test.rta\ap3
masmx -kw -Z ap3.msm ..\test.rta\ap3z
masmx -kw applaud.msm ..\test.rta\applaud
masmx -kw application.msm ..\test.rta\application
masmx -kw aqt.msm ..\test.rta\aqt
masmx -kw array.msm ..\test.rta\array
masmx -kw array2.msm ..\test.rta\array2
masmx -kw arrester.msm ..\test.rta\arrester
masmx -kw arrow.msm ..\test.rta\arrow
masmx -kw att.msm ..\test.rta\att
masmx -kw attestor.msm ..\test.rta\attestor
masmx -kw awibiti.msm ..\test.rta\awibiti
masmx -kw base_d.msm ..\test.rta\base_d
masmx -kw basis.msm ..\test.rta\basis
masmx -kw betaille.msm ..\test.rta\betaille
masmx -kw bloc_fun.msm ..\test.rta\bloc_fun
masmx -kw boolean.msm ..\test.rta\boolean
masmx -kw brin.msm ..\test.rta\brin
masmx -kw bsti.msm ..\test.rta\bsti
masmx -kw call4u.msm ..\test.rta\call4u
masmx -kw catalog.msm ..\test.rta\catalog
masmx -kw cdml.msm ..\test.rta\cdml
masmx -kw chaos.msm ..\test.rta\chaos
masmx -kw clatter.msm ..\test.rta\clatter
masmx -kw clibel.msm ..\test.rta\clibel
masmx -kw cluster.msm ..\test.rta\cluster
masmx -kw colibri.msm ..\test.rta\colibri
masmx -kw collect.msm ..\test.rta\collect
masmx -kw columns.msm ..\test.rta\columns
masmx -kw complete.msm ..\test.rta\complete
masmx -kw context.msm ..\test.rta\context
masmx -kw cs2i.msm ..\test.rta\cs2i
masmx -kw cstrings.msm ..\test.rta\cstrings
masmx -kw dmsa.msm ..\test.rta\dmsa
masmx -kw dmsample.msm ..\test.rta\dmsample
masmx -kw directio.msm ..\test.rta\directio
masmx -kw du.msm ..\test.rta\du
masmx -kw elephant.msm ..\test.rta\elephant
masmx -kw expand.msm ..\test.rta\expand
masmx -kw expound.msm ..\test.rta\expound
masmx -kw fields.msm ..\test.rta\fields
masmx -kw floating.msm ..\test.rta\floating
masmx -kw fpfactor.msm ..\test.rta\fpfactor
masmx -kw fplen.msm ..\test.rta\fplen
masmx -kw fp_array.msm ..\test.rta\fp_array
masmx -kw funs.msm ..\test.rta\funs
masmx -kw gamp.msm ..\test.rta\gamp
masmx -kw gant.msm ..\test.rta\gant
masmx -kw gap.msm ..\test.rta\gap
masmx -kw harness1.msm ..\test.rta\harness1
masmx -kw horror.msm ..\test.rta\horror
masmx -kw iarrayl.msm ..\test.rta\iarrayl
masmx -kw ibj.msm ..\test.rta\ibj
masmx -lnk idio.msm ..\test.rta\idio > newlist.txt
masmx -kw ilib12.msm ..\test.rta\ilib12
masmx -kw ilib16.msm ..\test.rta\ilib16
masmx -kw ilib16z.msm ..\test.rta\ilib16z
masmx -kw ilib6.msm ..\test.rta\ilib6
masmx -kw ilib24.msm ..\test.rta\ilib24
masmx -kw ilib.msm ..\test.rta\ilib
masmx -kw index.msm ..\test.rta\index
masmx -kw indicate.msm ..\test.rta\indicate
masmx -kw ipproto.msm ..\test.rta\ipproto
masmx -kw istrubl.msm ..\test.rta\istrubl
masmx -kw large.msm ..\test.rta\large
masmx -kw leftala.msm ..\test.rta\leftala
masmx -kw leveler.msm ..\test.rta\leveler
masmx -kw levels.msm ..\test.rta\levels
masmx -kw linkrel.msm ..\test.rta\linkrel
masmx -kw loademup.msm ..\test.rta\loademup
masmx -kw loadg.msm ..\test.rta\loadg
masmx -kw log2.msm ..\test.rta\log2
masmx -kw lquick.msm ..\test.rta\lquick
masmx -kw lstruct.msm ..\test.rta\lstruct
masmx -kw main.msm ..\test.rta\main
masmx -kw mammoth.msm ..\test.rta\mammoth
masmx -kw maru.msm ..\test.rta\maru
masmx -kw miklthon.msm ..\test.rta\miklthon
masmx -kw mstrlib.msm ..\test.rta\mstrlib
masmx -kw muklthon.msm ..\test.rta\muklthon
masmx -kw nawmuch.msm ..\test.rta\nawmuch
masmx -kw newtotal.msm ..\test.rta\newtotal
masmx -kw once.msm ..\test.rta\once
masmx -kw onetime.msm ..\test.rta\onetime
masmx -kw oreally.msm ..\test.rta\oreally
masmx -kw oreilly.msm ..\test.rta\oreilly
masmx -kw overlap.msm ..\test.rta\overlap
masmx -kw overlay.msm ..\test.rta\overlay
masmx -kw p1.msm ..\test.rta\p1
masmx -kw p2.msm ..\test.rta\p2
masmx -kw p3.msm ..\test.rta\p3
masmx -kw paxels.msm ..\test.rta\paxels
masmx -kw point.msm ..\test.rta\point
masmx -kw pointer.msm ..\test.rta\pointer
masmx -kw pointers.msm ..\test.rta\pointers
masmx -kw pungs.msm ..\test.rta\pungs
masmx -kw px8.msm ..\test.rta\px8
masmx -kw pygmalio.msm ..\test.rta\pygmalio
masmx -kw q.msm ..\test.rta\q
masmx -kw quadlib.msm ..\test.rta\quadlib
masmx -kw quickly.msm ..\test.rta\quickly
masmx -kw rabits.msm ..\test.rta\rabits
masmx -kw raft.msm ..\test.rta\raft
masmx -kw randomsi ..\test.rta\randomsi
masmx -kw rangy ..\test.rta\rangy
masmx -kw rasm.msm ..\test.rta\rasm
masmx -kw record.msm ..\test.rta\record
masmx -kw recurseg.msm ..\test.rta\recurseg
masmx -kw refine.msm ..\test.rta\refine
masmx -kw rei.msm ..\test.rta\rei
masmx -kw relarith.msm ..\test.rta\relarith
masmx -kw relocate.msm ..\test.rta\relocate
masmx -kw rodel.msm ..\test.rta\rodel
masmx -kw rtable.msm ..\test.rta\rtable
masmx -kw s.msm ..\test.rta\s
masmx -kw s2i.msm ..\test.rta\s2i
masmx -kw salute.msm ..\test.rta\salute
masmx -kw sand46.msm ..\test.rta\sand46
masmx -kw sand46_2.msm ..\test.rta\sand46_2
masmx -kw sand5.msm ..\test.rta\sand5
masmx -kw sand5_2.msm ..\test.rta\sand5_2
masmx -kw sandwich.msm ..\test.rta\sandwich
masmx -kw schema.msm ..\test.rta\schema
masmx -kw schema1.msm ..\test.rta\schema1
masmx -kw sema.msm ..\test.rta\sema
masmx -kw semi.msm ..\test.rta\semi
masmx -kw shadow.msm ..\test.rta\shadow
masmx -kw shadow1.msm ..\test.rta\shadow1
masmx -kw shuttle.msm ..\test.rta\shuttle
masmx -kw simply.msm ..\test.rta\simply -c
masmx -kw sizes.msm ..\test.rta\sizes
masmx -kw slappit.msm ..\test.rta\slappit
masmx -kw sort_out.msm ..\test.rta\sort_out
masmx -kw sowino.msm ..\test.rta\sowino
lstring -b ..\test.rta\sowino.txo ..\test.rta\sowino
masmx -kw soyuno.msm ..\test.rta\soyuno
masmx -kw spiko.msm ..\test.rta\spiko
masmx -kw splices.msm ..\test.rta\splices
masmx -kw spoka.msm ..\test.rta\spoka
masmx -kw step1.msm ..\test.rta\step1
masmx -kw step2.msm ..\test.rta\step2
masmx -kw step3.msm ..\test.rta\step3
masmx -kw step4.msm ..\test.rta\step4
masmx -kw stredit.msm ..\test.rta\stredit
masmx -kw subsequf ..\test.rta\subsequf
masmx -kw symbo.msm ..\test.rta\symbo
masmx -kw tcolumn.msm ..\test.rta\tcolumn
masmx -kw tptr.msm ..\test.rta\tptr
masmx -kw tryhard.msm ..\test.rta\tryhard
masmx -kw types.msm ..\test.rta\types
masmx -kw unary.msm ..\test.rta\unary
masmx -kw unary2.msm ..\test.rta\unary2
masmx -kw unlikely.msm ..\test.rta\unlikely
masmx -kw velours.msm ..\test.rta\velours
masmx -kw visible.msm ..\test.rta\visible
masmx -kw where.msm ..\test.rta\where
pushd ..\multadic
masmx -kw multadic ..\test.rta\multadic
cd ..\language
masmx -kw fpxample ..\test.rta\fpxample
masmx -kw fpxpress ..\test.rta\fpxpress
masmx -kw i_xpr ..\test.rta\i_xpr
masmx -kw individu ..\test.rta\individu
masmx -kw r2xample ..\test.rta\r2xample
popd
seeif -asvVW list.txt newlist.txt

